# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LJ' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LJ
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  #target 'LJ-tvOSTests' do
  #  inherit! :search_paths
   # Pods for testing
  #end

  target 'LJTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'LJ-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LJ-tvOS

  #target 'LJ-tvOSTests' do
  #  inherit! :search_paths
    # Pods for testing
  #end

end
